# Pandas b√°sico

In [1]:
import pandas as pd

BASE = "dados/cereal_sem_negativos.csv"

df = pd.read_csv(BASE)

df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541

In [2]:
df["total_carb"] = df["carbo"] + df["sugars"]
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,total_carb
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973,11.0
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679,16.0
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505,12.0
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912,8.0
4,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541,20.5

In [3]:
df["weight_grams"] = df["weight"] * 28.3495
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,total_carb,weight_grams
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973,11.0,28.3495
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679,16.0,28.3495
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505,12.0,28.3495
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912,8.0,28.3495
4,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541,20.5,28.3495

In [5]:
with pd.option_context("float_format", "{:.2f}".format):
    display(df.describe())

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,total_carb,weight_grams
count,74.00,74.00,74.00,74.00,74.00,74.00,74.00,74.00,74.00,74.00,74.00,74.00,74.00,74.00,74.00
mean,107.03,2.51,1.00,162.36,2.18,14.73,7.11,98.51,29.05,2.22,1.03,0.82,42.37,21.84,29.22
std,19.84,1.08,1.01,82.77,2.42,3.89,4.36,70.88,22.29,0.83,0.15,0.24,14.03,4.34,4.35
min,50.00,1.00,0.00,0.00,0.00,5.00,0.00,15.00,0.00,1.00,0.50,0.25,18.04,8.00,14.17
25%,100.00,2.00,0.00,135.00,0.25,12.00,3.00,41.25,25.00,1.25,1.00,0.67,32.45,20.00,28.35
50%,110.00,2.50,1.00,180.00,2.00,14.50,7.00,90.00,25.00,2.00,1.00,0.75,40.25,23.00,28.35
75%,110.00,3.00,1.00,217.50,3.00,17.00,11.00,120.00,25.00,3.00,1.00,1.00,50.52,25.00,28.35
max,160.00,6.00,5.00,320.00,14.00,23.00,15.00,330.00,100.00,3.00,1.50,1.50,93.70,30.00,42.52